version: '3.9'
services:
  api:
    build: .
    environment:
      - APP_PORT=8080
      - APP_ENV=dev
      - JWT_SECRET=change-me
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=notes
      - MYSQL_USER=notes
      - MYSQL_PASS=notes
      - CORS_ALLOW_ORIGINS=*
      - STORAGE_DIR=/var/app/storage
    ports:
      - "8080:8080"
    volumes:
      - storage:/var/app/storage
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=notes
      - MYSQL_USER=notes
      - MYSQL_PASSWORD=notes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8080"
volumes:
  db_data:
  storage:
